export const FETCH_ADMIN = "FETCH_ADMIN";
export const FETCH_ADMIN_VIEWUSERS = "FETCH_ADMIN_VIEWUSERS";
export const SESSION_COMPLETE = "SESSION_COMPLETE";

export const LOGIN_TRAINER ="LOGIN_TRAINER"
export const LOGOUT_TRAINER ="LOGOUT_TRAINER"